---
title: LFC’s Home and Away Wins
author: Ryan Estrellado
date: '2017-11-23'
slug: lfc-s-home-and-away-wins
categories: []
tags: []
---

```{r load packages}
#install.packages("engsoccerdata")
library(engsoccerdata)
library(tidyverse)
library(lubridate)
library(stringr)
library(rvest)
```

The managers and the years they managed Liverpool FC are scraped from the [Wikipedia page for LFC managers](https://en.wikipedia.org/wiki/List_of_Liverpool_F.C._managers).

```{r scrape manager data}
site <- read_html(
  "https://en.wikipedia.org/wiki/List_of_Liverpool_F.C._managers"
  )

mtable <- site %>%
  html_nodes("table") %>%
  .[[3]] %>%
  html_table(fill = T) %>%
  as_tibble()
```

```{r}
# Clean up fields
mngrs_clean <- mtable %>%
  # The first row are field names
  filter(row_number() != 1) %>% 
  # Clean up the manager names
  mutate(Name = str_replace(Name, "\\,.*", ""), 
         # Fix the name for the Evans and Houllier era
         Name = ifelse(Name == "Evans" & Nationality != "England", 
                       "Evans & Houllier", 
                       Name)) %>% 
  # Remove zeros and strange characters
  mutate_at(c("From", "To"), funs(str_sub(., 9, 18))) %>% 
  select(From, To, Name)

# Convert classes
mngrs_clean <- mngrs_clean %>%
  mutate_at(vars(From:To), funs(ymd)) %>% 
  # Use today's date in the latest manager's "To" field 
  mutate(To = if_else(row_number() == nrow(mngrs_clean), Sys.Date(), To))
```

```{r create lfc tibble}
# Subset Liverpool home and away games
lfc <- as.tibble(england) %>%
  mutate(Date = ymd(Date)) %>% 
  mutate_at(vars(home:FT, result), funs(as.character)) %>%
  mutate_at(vars(hgoal:goaldif), funs(as.numeric)) %>%
  filter(home == "Liverpool" | visitor == "Liverpool") %>% 
  # Create a new column for managers 
  mutate(mngr = "") %>%
  arrange(Date)
```

```{r}
# TODO: Can we do this as a function by creating a vector of manager names?
# TODO: Deal with rows that have no manager
for (i in 1:nrow(mngrs_clean)) {
 lfc <- lfc %>% 
  mutate(mngr = ifelse(Date >= mngrs_clean$From[i] & Date <= mngrs_clean$To[i], 
    mngrs_clean$Name[i], 
    mngr))
}
```

```{r}
# New goals column and at Anfield column
lfc <- lfc %>% 
  mutate(lfc_goals = 0, 
         lfc_goals = ifelse(home == "Liverpool", hgoal, vgoal), 
         at_anf = "", 
         at_anf = ifelse(home == "Liverpool", "Anfield", "Away"))
```

## Comparing Win Ratios

```{r}
win_ratios <- lfc %>% 
  mutate(win = 0,
         win = ifelse(home == "Liverpool" & result == "H", 1, win), 
         win = ifelse(visitor == "Liverpool" & result == "A", 1, win)) %>% 
  select(mngr, at_anf, win) %>% 
  group_by(mngr) %>% 
  summarise(total_hwins = sum(at_anf == "Anfield" & win == 1), 
            total_hgames = sum(at_anf == "Anfield"), 
            total_awins = sum(at_anf != "Anfield" & win == 1), 
            total_agames = sum(at_anf != "Anfield")) %>% 
  ungroup() %>% 
  mutate(h_odds = (total_hwins / total_hgames) / (1 - total_hwins / total_hgames), 
         a_odds = (total_awins / total_agames) / (1 - total_awins / total_agames), 
         log_odds_ratio = log2(h_odds / a_odds)) %>% 
  filter(total_hgames + total_agames >= 30)
```

```{r}
ggplot(data = win_ratios, aes(x = reorder(mngr, log_odds_ratio), 
                              y = log_odds_ratio, 
                              color = log_odds_ratio < 0)) + 
  geom_point(aes(size = total_hgames + total_agames), 
             alpha = .9) + 
  geom_segment(aes(x = mngr, xend = mngr, y = 0, yend = log_odds_ratio), 
               size = 1) +
  coord_flip() + 
  scale_color_discrete(name = "", labels = c("More home wins", "More away wins")) +
  scale_y_continuous(breaks = seq(-3, 3), 
                     limits = c(-1, 3),
                     labels = c(".125x", ".25", ".5x", "same", "2x more", "4x", "8x")) +
  labs(title = "Klopp Wins More Away Games But Time Will Tell", 
       subtitle = "Top Flight League Games 1893 - 2016", 
       x = "", y = "Liverpool Home Wins Odds vs. Away Wins Odds", size = "Total Games")
```