---
title: Introducing Data Science Into Your Education Job
author: Ryan Estrellado
date: '2018-05-22'
slug: introducing-data-science-into-your-education-job
categories: []
tags: []
draft: TRUE
---

Sometimes new tools get conflated with the professional identity of the person using those tools. For example, there was a time when the standard for writing essays was to use pen and paper. During that time if you were one of the few who used a word processor, you might have been thought of as "that computer person." Now that the use of Microsoft Word is more or less an expected office skill, we no longer see the use of word processors as the professional identity of the person using them. They are simply writers, accountants, teachers, or artists who use tools that accelerate their writing process. 

During this period of time when data science processes aren't commonly seen in public education, it can be challenging to introduce data science techniques into your data routine because most people in public education don't carry the title "data scientist." The key here is to reframe your efforts by seeing yourself as a teacher who accelerates their teaching by using data science techniques.  

Find a task you usually complete using Google Sheets or Excel and do it in R instead. 
Read up on a cognitive bias and try to combat it by doing a data analysis. 

Listen carefully at meetings and take notice when the same analytic question comes up repeatedly. If your teammates keep saying behavior referrals seem to be growing every year, tackle that question with your data science skills. 

Automate a frequently data report by using an R Notebook. 

Use R to reproduce another agency's data findings. 

Use your data skills to answer a typical data question. Then go deeper and answer a few more. For example, maybe your grade level team wants to know the average score of all fifth grade students on last week's quiz. You can write up some code to answer that question, then encourage deeper thinking by looping that code over the last 4 weeks worth of quiz scores. 