---
title: 'California School Dashboards Part 3: Modeling the Data '
author: Ryan Estrellado
date: '2018-03-28'
slug: california-school-dashboards-part-3-modeling-the-data
categories: []
tags:
  - school_data
  - tidyverse 
draft: TRUE
---

```{r echo=FALSE, message=FALSE}
library(tidyverse) 
library(modelr) 
library(knitr) 
library(spedtools)
```

```{r echo=FALSE}
opts_chunk$set(echo = FALSE, message = FALSE)
```

```{r}
# Read data 
urls <- c(
  "https://raw.githubusercontent.com/restrellado/data_for_blog/master/dashboard_model_data/district_1.tsv", 
  "https://raw.githubusercontent.com/restrellado/data_for_blog/master/dashboard_model_data/district_2.tsv", 
  "https://raw.githubusercontent.com/restrellado/data_for_blog/master/dashboard_model_data/district_3.tsv", 
  "https://raw.githubusercontent.com/restrellado/data_for_blog/master/dashboard_model_data/district_4.tsv", 
  "https://raw.githubusercontent.com/restrellado/data_for_blog/master/dashboard_model_data/district_5.tsv", 
  "https://raw.githubusercontent.com/restrellado/data_for_blog/master/dashboard_model_data/district_6.tsv", 
  "https://raw.githubusercontent.com/restrellado/data_for_blog/master/dashboard_model_data/district_7.tsv", 
  "https://raw.githubusercontent.com/restrellado/data_for_blog/master/dashboard_model_data/district_8.tsv", 
  "https://raw.githubusercontent.com/restrellado/data_for_blog/master/dashboard_model_data/district_9.tsv"
) 

all_files <- urls %>% 
  map(., read_tsv) %>% 
  set_names(., nm = map_chr(., ~unique(.$districtname)))
```

```{r}
all_files[[1]] %>% 
  # Remove school level datapoints 
  filter(!is.na(schoolname)) %>%
  ggplot(aes(x = currstatus_math, y = currstatus_ela)) + 
  geom_point() + 
  geom_smooth(method = "loess") +
  labs(title = "Distance from Three: Math vs. English Language Arts", 
       x = "Math Dist from Three", y = "ELA Dist from Three")
```

```{r}
comb <- all_files %>% 
  bind_rows() %>% 
  # Remove district level observations, only include subgroups
  filter(!is.na(schoolname), studentgroup != "ALL") %>% 
  mutate(studentgroup = convert_subgroup(studentgroup)) %>% 
  # Nest datasets by district
  group_by(districtname) %>% 
  nest() 
comb
```

```{r}
dist_mod <- function(d) {
  lm(currstatus_ela ~ currstatus_math, data = d)
}

mods <- comb %>% 
  mutate(model = map(data, dist_mod), 
         resids = map2(data, model, add_residuals)) 
mods
```

[Definition of EL and ELO](https://www.cde.ca.gov/ta/ac/cm/documents/dashboardguidespring17.pdf) 

```{r}
resids <- mods %>% 
  unnest(resids) %>% 
  mutate(el = ifelse(studentgroup == "English Learners Only", TRUE, FALSE))

ggplot(data = resids, aes(x = currstatus_math, y = resid, color = el)) + 
  geom_point(alpha = .5) + 
  facet_wrap(~ districtname)
```

